// ShipperShop Messages — Filter + Search + Categories
var curFilter="",curSearch="",searchTimer=null,catData=[],ctxConvId=0,ctxConvName="";
function onSearchInput(v){clearTimeout(searchTimer);curSearch=v.trim();searchTimer=setTimeout(function(){applyFilter();},300);}
function setFilter(el,f){document.querySelectorAll(".f-chip").forEach(function(c){c.classList.remove("active");});el.classList.add("active");curFilter=f;if(f==="groups"){loadGroupConvs();return;}if(f==="strangers"){curTab="pending";loadConvs();return;}if(f===""){curTab="active";curSearch="";document.getElementById("searchInput").value="";}applyFilter();}
function applyFilter(){if(curFilter===""&&curSearch===""){loadConvs();return;}var url="/api/messages-api.php?action=filter_conversations&filter="+encodeURIComponent(curFilter)+"&search="+encodeURIComponent(curSearch);if(curFilter==="category"){var ac=document.querySelector(".f-chip.active[data-cat-id]");if(ac)url+="&category_id="+ac.getAttribute("data-cat-id");}var list=document.getElementById("convList");list.innerHTML="<div class=empty><i class='fas fa-spinner fa-spin'></i></div>";fetch(url,{credentials:"include"}).then(function(r){return r.json();}).then(function(d){if(!d.success||!d.data.length){list.innerHTML="<div class=empty><i class='far fa-comment-dots'></i><p>Không tìm thấy</p></div>";return;}list.innerHTML=d.data.map(function(c){return renderConvItem(c);}).join("");attachLongPress();}).catch(function(){list.innerHTML="<div class=empty><p>Lỗi</p></div>";});}
function renderConvItem(c){var av=c.other_avatar?"<img class=cv-av src='"+c.other_avatar+"' onerror='this.className=\"cv-av-ph\";this.innerHTML=\""+(c.other_name||"U").charAt(0)+"\"' loading=\"lazy\">":"<div class=cv-av-ph>"+(c.other_name||"U").charAt(0)+"</div>";var dot=parseInt(c.other_online)?"<div class=cv-dot></div>":"";var ship=c.other_ship?"<span class=cv-ship style=color:"+(SC[c.other_ship]||"#999")+">"+esc(c.other_ship)+"</span>":"";var unread=parseInt(c.unread_count)>0;var cb="";if(c.category_id&&catData.length){for(var i=0;i<catData.length;i++){if(parseInt(catData[i].id)===parseInt(c.category_id)){cb=" <span style='font-size:10px;background:"+catData[i].color+";color:#fff;padding:1px 6px;border-radius:8px'>"+esc(catData[i].name)+"</span>";break;}}}return "<div class='conv-item"+(unread?" unread":"")+"' data-conv-id='"+c.id+"' onclick='openConv("+c.id+","+c.other_id+",\""+esc(c.other_name)+"\",\""+esc(c.other_avatar||"")+"\","+c.other_online+",\""+esc(c.other_ship||"")+"\")'>"+
"<div class=cv-av-wrap>"+av+dot+"</div>"+
"<div class=cv-info><div class=cv-name>"+esc(c.other_name)+" "+ship+cb+"</div><div class=cv-last>"+esc((c.last_message||"").substring(0,40))+"</div></div>"+
"<div class=cv-right><div class=cv-time>"+ago(c.last_message_at)+"</div>"+(unread?"<div class=cv-unread></div>":"")+"</div></div>";}
function loadCategories(){fetch("/api/messages-api.php?action=get_categories",{credentials:"include"}).then(function(r){return r.json();}).then(function(d){if(d.success)catData=d.data||[];renderCatChips();}).catch(function(){});}
function renderCatChips(){var c=document.getElementById("filterChips");c.querySelectorAll(".f-chip[data-cat-id]").forEach(function(e){e.remove();});var ref=document.getElementById("chipCategories");catData.forEach(function(d){var b=document.createElement("button");b.className="f-chip";b.setAttribute("data-filter","category");b.setAttribute("data-cat-id",d.id);b.innerHTML=d.icon+" "+d.name+(parseInt(d.conv_count)>0?" <span style='font-size:11px;color:#65676B'>("+d.conv_count+")</span>":"");b.onclick=function(){document.querySelectorAll(".f-chip").forEach(function(x){x.classList.remove("active");});b.classList.add("active");curFilter="category";applyFilter();};c.insertBefore(b,ref);});}
function openCatManager(){document.getElementById("catSheetTitle").textContent="Phân loại";document.getElementById("catOverlay").classList.add("show");renderCatList();}
function closeCatManager(){document.getElementById("catOverlay").classList.remove("show");}
function renderCatList(){var el=document.getElementById("catList");if(!catData.length){el.innerHTML="<div class=empty style='padding:30px'><p>Chưa có phân loại nào</p></div>";return;}el.innerHTML=catData.map(function(c){return "<div class=cat-item><div class=cat-icon style='background:"+c.color+"20;color:"+c.color+"'>"+c.icon+"</div><div class=cat-info><div class=cat-name>"+esc(c.name)+"</div><div class=cat-count>"+(parseInt(c.conv_count)||0)+" đoạn chat</div></div><button class=cat-del onclick='event.stopPropagation();deleteCat("+c.id+",\""+esc(c.name)+"\")' ><i class='fas fa-trash'></i></button></div>";}).join("");}
function saveCat(){var inp=document.getElementById("catNameInput");var n=inp.value.trim();if(!n)return;inp.value="";var icons=["📁","📦","🏷","⭐","💼","🔔","👥","❤️","🚚","💰"];var colors=["#0084ff","#00b14f","#7C3AED","#9b59b6","#e67e22","#e74c3c","#1abc9c","#f39c12","#3498db","#2c3e50"];fetch("/api/messages-api.php?action=save_category",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({name:n,icon:icons[catData.length%icons.length],color:colors[catData.length%colors.length]})}).then(function(r){return r.json();}).then(function(d){if(d.success){loadCategories();setTimeout(renderCatList,500);}}).catch(function(){});}
function deleteCat(id,name){if(!confirm("Xóa phân loại \""+name+"\"?"))return;fetch("/api/messages-api.php?action=delete_category",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({id:id})}).then(function(r){return r.json();}).then(function(d){if(d.success){loadCategories();setTimeout(renderCatList,500);}}).catch(function(){});}
function attachLongPress(){document.querySelectorAll(".conv-item[data-conv-id]").forEach(function(el){var tm=null;el.addEventListener("touchstart",function(e){tm=setTimeout(function(){e.preventDefault();ctxConvId=parseInt(el.getAttribute("data-conv-id"));ctxConvName=el.querySelector(".cv-name")?el.querySelector(".cv-name").textContent:"";showCtxMenu(e.touches[0].clientX,e.touches[0].clientY);},500);},{passive:false});el.addEventListener("touchend",function(){clearTimeout(tm);});el.addEventListener("touchmove",function(){clearTimeout(tm);});});}
function showCtxMenu(x,y){var m=document.getElementById("ctxMenu");m.style.left=Math.min(x,window.innerWidth-220)+"px";m.style.top=Math.min(y,window.innerHeight-100)+"px";m.classList.add("show");setTimeout(function(){document.addEventListener("click",hideCtxMenu,{once:true});},10);}
function hideCtxMenu(){document.getElementById("ctxMenu").classList.remove("show");}
function openAssignCat(){hideCtxMenu();if(!ctxConvId)return;document.getElementById("catSheetTitle").textContent="Phân loại: "+ctxConvName.substring(0,20);document.getElementById("catOverlay").classList.add("show");fetch("/api/messages-api.php?action=get_chat_category&conversation_id="+ctxConvId,{credentials:"include"}).then(function(r){return r.json();}).then(function(d){var cc=d.success?parseInt(d.data.category_id):0;var el=document.getElementById("catList");var h="<div class=cat-item onclick='assignCat(0)'><div class=cat-icon style='background:#f0f2f5'>✕</div><div class=cat-info><div class=cat-name>Không phân loại</div></div>"+(cc===0?"<div class=cat-check><i class='fas fa-check-circle'></i></div>":"")+"</div>";h+=catData.map(function(c){var s=parseInt(c.id)===cc;return "<div class=cat-item onclick='assignCat("+c.id+")'><div class=cat-icon style='background:"+c.color+"20;color:"+c.color+"'>"+c.icon+"</div><div class=cat-info><div class=cat-name>"+esc(c.name)+"</div></div>"+(s?"<div class=cat-check><i class='fas fa-check-circle'></i></div>":"")+"</div>";}).join("");el.innerHTML=h;}).catch(function(){});}
function assignCat(catId){fetch("/api/messages-api.php?action=set_chat_category",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({conversation_id:ctxConvId,category_id:catId})}).then(function(r){return r.json();}).then(function(d){if(d.success){closeCatManager();loadCategories();if(curFilter)applyFilter();else loadConvs();}}).catch(function(){});}
function markConvRead(){hideCtxMenu();if(!ctxConvId)return;fetch("/api/messages-api.php?action=read",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({conversation_id:ctxConvId})}).then(function(){loadConvs();});}
function fixListPadding(){var tb=document.getElementById("topBar");if(tb){var h=tb.offsetHeight;var ob=document.getElementById("onlineBarMargin");if(ob)ob.style.marginTop=h+"px";document.querySelector(".list-view").style.paddingTop=h+"px";}}
loadCategories();setTimeout(fixListPadding,100);setTimeout(function(){attachLongPress();},1000);window.addEventListener("resize",fixListPadding);
