// ShipperShop people.html

var CU=JSON.parse(localStorage.getItem('user')||'null');if(!CU)location.href='login.html';
var allFriends=[],allRequests=[],allSuggestions=[],curTab='online';
var shipColors={'GHTK':'#00b14f','J&T':'#d32f2f','GHN':'#ff6600','SPX':'#7C3AED','Grab':'#00b14f','Be':'#5bc500','Gojek':'#00aa13','Ninja Van':'#c41230','Viettel Post':'#e21a1a'};
async function loadAll(){await Promise.all([loadFriends(),loadRequests(),loadSuggestions()]);renderTab();}
async function loadFriends(){try{var r=await fetch('/api/friends.php?action=list',{credentials:'include'});var d=await r.json();if(d.success)allFriends=d.data;}catch(e){}}
async function loadRequests(){try{var r=await fetch('/api/friends.php?action=requests',{credentials:'include'});var d=await r.json();if(d.success){allRequests=d.data;var b=document.getElementById('reqBadge');if(allRequests.length>0){b.style.display='inline';b.textContent=allRequests.length;}}}catch(e){}}
async function loadSuggestions(){try{var r=await fetch('/api/friends.php?action=suggestions',{credentials:'include'});var d=await r.json();if(d.success)allSuggestions=d.data;}catch(e){}}
function setTab(tab,el){curTab=tab;document.querySelectorAll('.tab').forEach(function(t){t.classList.remove('active');});el.classList.add('active');renderTab();}
function renderTab(){var c=document.getElementById('content');var search=document.getElementById('searchInput').value.toLowerCase();
if(curTab==='online'){var online=allFriends.filter(function(f){return f.is_online&&(!search||f.fullname.toLowerCase().indexOf(search)>-1);});var offline=allFriends.filter(function(f){return !f.is_online&&(!search||f.fullname.toLowerCase().indexOf(search)>-1);});
if(online.length){document.getElementById('storiesBar').style.display='flex';document.getElementById('storiesBar').innerHTML=online.map(function(f){var av=f.avatar?'<img src="'+f.avatar+'" loading=lazy>':'<div style="background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:18px;width:60px;height:60px;border-radius:50%">'+((f.fullname||'U').charAt(0))+'</div>';return '<div class="story-av" onclick="location.href=\'messages.html?user='+f.id+'\'">'+av+'<div class="online"></div><div class="story-name">'+esc((f.fullname||'').split(' ').pop())+'</div></div>';}).join('');}else document.getElementById('storiesBar').style.display='none';
var html='';if(online.length){html+='<div class="section-title"><span style="color:#22c55e">●</span> '+online.length+' đang hoạt động</div>';html+=online.map(function(f){return mkPerson(f,true);}).join('');}if(offline.length){html+='<div class="section-title">Ngoại tuyến</div>';html+=offline.map(function(f){return mkPerson(f,false);}).join('');}if(!online.length&&!offline.length)html='<div class="empty"><i class="fas fa-users"></i><p>Chưa có bạn bè</p></div>';c.innerHTML=html;}
if(curTab==='all'){document.getElementById('storiesBar').style.display='none';var friends=allFriends.filter(function(f){return !search||f.fullname.toLowerCase().indexOf(search)>-1;});var html='';if(friends.length){html+='<div class="section-title"><i class="fas fa-user-check"></i> Bạn bè ('+friends.length+')</div>';html+=friends.map(function(f){return mkPerson(f,f.is_online);}).join('');}if(allSuggestions.length){html+='<div class="section-title"><i class="fas fa-user-plus"></i> Gợi ý kết bạn</div>';html+=allSuggestions.filter(function(f){return !search||f.fullname.toLowerCase().indexOf(search)>-1;}).map(function(f){return mkSuggestion(f);}).join('');}if(!html)html='<div class="empty"><i class="fas fa-users"></i><p>Không tìm thấy</p></div>';c.innerHTML=html;}
if(curTab==='requests'){document.getElementById('storiesBar').style.display='none';if(!allRequests.length){c.innerHTML='<div class="empty"><i class="fas fa-user-clock"></i><p>Không có lời mời</p></div>';return;}c.innerHTML='<div class="section-title"><i class="fas fa-user-clock"></i> Lời mời ('+allRequests.length+')</div>'+allRequests.map(function(r){return mkRequest(r);}).join('');}}
function mkPerson(f,online){var av=f.avatar?'<img src="'+f.avatar+'" class="p-av" loading=lazy>':'<div class="p-av" style="background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:18px">'+((f.fullname||'U').charAt(0))+'</div>';var ship=f.shipping_company?'<span style="color:'+(shipColors[f.shipping_company]||'#999')+'"> '+esc(f.shipping_company)+'</span>':'';var sub=online?'<span style="color:#22c55e">Đang hoạt động</span>':f.last_active?'Hoạt động '+ago(f.last_active):'';return '<div class="person-item" onclick="location.href=\'user.html?id='+f.id+'\'"><div class="p-av-wrap">'+av+(online?'<div class="p-online"></div>':'')+'</div><div class="p-info"><div class="p-name">'+esc(f.fullname)+ship+'</div><div class="p-sub">'+sub+'</div></div><div><button class="p-btn secondary" onclick="event.stopPropagation();location.href=\'messages.html?user='+f.id+'\'"><i class="fas fa-comment-dots"></i></button></div></div>';}
function mkSuggestion(f){var av=f.avatar?'<img src="'+f.avatar+'" class="p-av" loading=lazy>':'<div class="p-av" style="background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:18px">'+((f.fullname||'U').charAt(0))+'</div>';return '<div class="person-item" onclick="location.href=\'user.html?id='+f.id+'\'"><div class="p-av-wrap">'+av+'</div><div class="p-info"><div class="p-name">'+esc(f.fullname)+'</div><div class="p-sub">'+esc(f.shipping_company||'')+'</div></div><div><button class="p-btn primary" onclick="event.stopPropagation();addFriend('+f.id+',this)"><i class="fas fa-user-plus"></i> Kết bạn</button></div></div>';}
function mkRequest(r){var av=r.avatar?'<img src="'+r.avatar+'" class="p-av" loading=lazy>':'<div class="p-av" style="background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:18px">'+((r.fullname||'U').charAt(0))+'</div>';return '<div class="person-item"><div class="p-av-wrap">'+av+'</div><div class="p-info"><div class="p-name">'+esc(r.fullname)+'</div><div class="p-sub">'+esc(r.shipping_company||'')+' · '+ago(r.created_at)+'</div></div><div class="req-actions"><button class="p-btn primary" onclick="acceptFriend('+r.id+',this.parentElement.parentElement)">Chấp nhận</button><button class="p-btn secondary" onclick="rejectFriend('+r.id+',this.parentElement.parentElement)">Từ chối</button></div></div>';}
async function addFriend(id,btn){try{var r=await fetch('/api/friends.php?action=add',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({friend_id:id})});var d=await r.json();if(d.success){btn.outerHTML='<button class="p-btn secondary" disabled>Đã gửi</button>';toast('Đã gửi lời mời!');}else toast(d.message);}catch(e){toast('Lỗi');}}
async function acceptFriend(id,el){try{var r=await fetch('/api/friends.php?action=accept',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({friend_id:id})});var d=await r.json();if(d.success){el.remove();toast('Đã chấp nhận!');loadAll();}}catch(e){toast('Lỗi');}}
async function rejectFriend(id,el){try{await fetch('/api/friends.php?action=reject',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({friend_id:id})});el.remove();toast('Đã từ chối');}catch(e){toast('Lỗi');}}
function filterPeople(){renderTab();}
function esc(t){if(!t)return'';return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function ago(dt){if(!dt)return'';var s=Math.floor((new Date()-new Date(dt.replace(' ','T')))/1000);if(s<60)return'Vừa xong';if(s<3600)return Math.floor(s/60)+' phút trước';if(s<86400)return Math.floor(s/3600)+' giờ trước';return Math.floor(s/86400)+' ngày trước';}
function toast(msg){var t=document.getElementById('toast');t.textContent=msg;t.className='toast show';setTimeout(function(){t.classList.remove('show');},2500);}
loadAll();
