<?php
/**
 * SHIPPERSHOP - DATABASE CONFIGURATION
 * Auto-generated by Setup Wizard
 */

defined('APP_ACCESS') or define('APP_ACCESS', true);

// DATABASE
define('DB_HOST', 'localhost');
define('DB_NAME', 'nhshiw2j_shippershop');
define('DB_USER', 'nhshiw2j_kudo9shinichi');
define('DB_PASS', 'Kudo9shinichi@');
define('DB_CHARSET', 'utf8mb4');

// SITE
define('SITE_URL', 'https://shippershop.vn');
define('SITE_NAME', 'ShipperShop');
define('SITE_EMAIL', 'support@shippershop.vn');
define('ADMIN_EMAIL', 'nguyenhuyneu1999@gmail.com');

// SECURITY
define('SECRET_KEY', 'f4262e5668c4d6b3fb5c3d9acc1471ea');
define('PASSWORD_SALT', '59987775bb76b123');
define('JWT_SECRET', '12a45d2132717424f75b21e997949331');
define('SESSION_LIFETIME', 86400);
define('SESSION_NAME', 'SHIPPERSHOP_SESSION');
define('PASSWORD_MIN_LENGTH', 6);
define('PASSWORD_REQUIRE_UPPERCASE', false);
define('PASSWORD_REQUIRE_NUMBER', false);

// PAYMENT
define('SHIPPING_FEE', 30000);
define('FREE_SHIPPING_THRESHOLD', 500000);
define('PAYMENT_COD', 'cod');
define('PAYMENT_BANK', 'bank_transfer');
define('PAYMENT_WALLET', 'wallet');
define('BANK_NAME', 'Vietcombank');
define('BANK_ACCOUNT', '1234567890');
define('BANK_OWNER', 'SHIPPERSHOP JSC');

// UPLOAD
define('UPLOAD_DIR', __DIR__ . '/../uploads/');
define('UPLOAD_MAX_SIZE', 5 * 1024 * 1024);
define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/png', 'image/gif', 'image/webp']);

// API
define('API_RATE_LIMIT', 200);
define('API_PAGINATION_LIMIT', 50);
define('API_DEFAULT_LIMIT', 12);

// ERROR
define('DEBUG_MODE', false);
error_reporting(0);
ini_set('display_errors', 0);

// TIMEZONE
date_default_timezone_set('Asia/Ho_Chi_Minh');

// SESSION
ini_set('session.cookie_httponly', 1);
ini_set('session.use_only_cookies', 1);
ini_set('session.gc_maxlifetime', SESSION_LIFETIME);
if (session_status() === PHP_SESSION_NONE) {
    session_name(SESSION_NAME);
    session_start();
}

// CORS
define('ALLOWED_ORIGINS', ['https://shippershop.vn', 'https://www.https://shippershop.vn']);

function setCorsHeaders() {
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With');
    header('Access-Control-Allow-Credentials: true');
    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(200); exit; }
}

function generateRandomString($length = 32) { return bin2hex(random_bytes($length / 2)); }
function hashPassword($password) { return password_hash($password, PASSWORD_BCRYPT); }
function verifyPassword($password, $hash) { return password_verify($password, $hash); }
function isLoggedIn() { return isset($_SESSION['user_id']) && !empty($_SESSION['user_id']); }
function getCurrentUserId() { return $_SESSION['user_id'] ?? null; }
function isAdmin() { return isset($_SESSION['user_role']) && $_SESSION['user_role'] === 'admin'; }

function requireAuth() {
    if (!isLoggedIn()) {
        http_response_code(401);
        echo json_encode(['success' => false, 'message' => 'Vui lòng đăng nhập']);
        exit;
    }
}

function requireAdmin() {
    requireAuth();
    if (!isAdmin()) {
        http_response_code(403);
        echo json_encode(['success' => false, 'message' => 'Không có quyền admin']);
        exit;
    }
}

function generateJWT($userId, $email, $role = 'user') {
    $header = base64_encode(json_encode(['alg' => 'HS256', 'typ' => 'JWT']));
    $payload = base64_encode(json_encode(['user_id' => $userId, 'email' => $email, 'role' => $role, 'iat' => time(), 'exp' => time() + SESSION_LIFETIME]));
    $signature = base64_encode(hash_hmac('sha256', "$header.$payload", JWT_SECRET, true));
    return "$header.$payload.$signature";
}

function verifyJWT($token) {
    $parts = explode('.', $token);
    if (count($parts) !== 3) return false;
    list($header, $payload, $signature) = $parts;
    $validSig = base64_encode(hash_hmac('sha256', "$header.$payload", JWT_SECRET, true));
    if ($signature !== $validSig) return false;
    $data = json_decode(base64_decode($payload), true);
    if ($data['exp'] < time()) return false;
    return $data;
}

return true;
