<?php
set_time_limit(180);
require_once '/home/nhshiw2j/public_html/includes/db.php';
$d=db();$pdo=$d->getConnection();
$batch=intval($_GET['b'] ?? 1);

// Content per group (35 posts each × 12 groups = 420)
$groupPosts = [
// Group 1: Shipper GHTK (35 posts)
1 => [
"App GHTK hôm nay update mới, giao diện đẹp hơn. Ae đã cập nhật chưa?",
"Chia sẻ: Cách nhận nhiều đơn GHTK hơn vào giờ cao điểm 🔥",
"GHTK vừa tăng chiết khấu 2% cho shipper có rating 4.5+ ⭐",
"Hỏi ae: Phí GHTK tính theo km hay theo khu vực? Mình mới join",
"Tháng này GHTK có chương trình thưởng extra 500k cho top 100 shipper",
"Bug app GHTK: Đơn hiện trên app nhưng nhận không được. Ai bị giống?",
"Review 1 năm chạy GHTK: Đơn đều, app ổn, hỗ trợ nhanh. 8/10",
"GHTK khu Q.7 đơn nhiều lắm ae. Ai chưa đăng ký khu này thì nên thử",
"Mẹo: Bật thông báo GHTK lúc 6h sáng để nhận đơn sớm nhất",
"Lương GHTK tháng 3: 16.5 triệu. Chạy 8h/ngày, 26 ngày. Ae tham khảo",
"GHTK vs GHN: Mình chạy cả 2, GHTK đơn nhiều hơn ở ngoại thành",
"Ae GHTK: Có cách nào filter đơn theo quận không? App hiện lẫn lộn",
"Hôm nay GHTK bảo trì server 30 phút. Ae tranh thủ nghỉ ngơi ☕",
"Chia sẻ: Đơn GHTK COD trả tiền nhanh hơn trước, chỉ 1-2 ngày",
"GHTK mới thêm tính năng chat với khách. Tiện hơn gọi điện nhiều!",
"Kinh nghiệm: Luôn check đơn GHTK trước khi rời kho, thiếu hàng phiền lắm",
"GHTK khu Bình Dương đơn tăng 40% sau Tết. Ae nào rảnh qua đây",
"Hỏi: Làm sao để lên hạng shipper VIP trên GHTK? Cần bao nhiêu đơn?",
"Tip: Giao đơn GHTK hoàn nhanh để giữ rating cao. Đừng delay quá 2h",
"GHTK vừa mở thêm điểm giao nhận ở Q.12. Thuận tiện hơn trước!",
"Ae GHTK có ai bị trừ phí bất thường tháng này không? Kiểm tra app nhé",
"Chia sẻ route chạy GHTK hiệu quả: Q7→Q4→Q8→Bình Chánh. 45 đơn/ngày",
"GHTK support phản hồi nhanh hơn trước. Ticket xử lý trong 2h",
"Review xe máy tốt nhất cho GHTK: Wave Alpha tiết kiệm, Air Blade nhanh",
"GHTK khu Gò Vấp: Hẻm nhiều nhưng đơn density cao, kiếm tốt",
"Hôm nay giao kỷ lục 58 đơn GHTK. Mệt nhưng thấy số tiền là quên mệt 💪",
"GHTK mới có bảo hiểm cho shipper. 50k/tháng, cover tai nạn 20 triệu",
"Ae GHTK khu Tân Phú: Đường Lũy Bán Bích giờ chiều kẹt cứng, tránh nhé",
"Mẹo GHTK: Nhận đơn gần nhau để tối ưu route, đừng nhận đơn quá xa",
"GHTK cuối năm bonus 1 triệu cho shipper trên 1000 đơn/tháng 🎉",
"Hỏi ae senior: GHTK có cho chạy đồng thời với hãng khác không?",
"Chia sẻ: Cách xử lý khi khách GHTK hẹn giao lại. Đừng hủy, đổi slot",
"GHTK app bị lag trên Android cũ. Ai có cách fix không? Clear cache rồi",
"Tổng kết 2 năm chạy GHTK: Kiếm được 350 triệu, mua được xe SH 🏍️",
"GHTK cảm ơn ae shipper! Không có chúng ta thì hàng ai giao 🙏",
],
// Group 2: Shipper Grab - Be - Gojek (35)
2 => [
"Grab mới đổi cách tính phí. Thu nhập tăng hay giảm ae? 🤔",
"So sánh: Grab đơn nhiều, Be phí thấp, Gojek bonus hấp dẫn. Ae chạy gì?",
"Hôm nay Grab surge x3 lúc 6h chiều khu Q.1. Kiếm 500k trong 2h!",
"Be vừa update app mới, giao diện giống Grab hơn. Ai thấy ok không?",
"Gojek khuyến mãi cho rider mới: 2 triệu bonus cho 100 đơn đầu",
"Mẹo Grab: Chạy khu trung tâm giờ trưa, đơn food nhiều + tip cao",
"Confession: Chạy Grab 3 app cùng lúc. Mệt nhưng thu nhập gấp đôi 😅",
"Be mới có GoBike. Chở khách + giao hàng. Ae đã đăng ký chưa?",
"Review 6 tháng chạy Gojek: Đơn ít hơn Grab nhưng phí cao hơn",
"Grab vs taxi truyền thống: Shipper công nghệ linh hoạt hơn nhiều",
"Ae Grab: Cách tăng rating lên 4.9+ để nhận nhiều đơn tốt hơn",
"Be đang mở rộng ở Đà Nẵng. Ae ĐN nên đăng ký sớm, ít cạnh tranh",
"Hôm nay chạy Grab food giao cho celeb. Starstruck 5 giây 😂",
"Gojek bonus tháng: 3 triệu cho 500 đơn. Ae cày được không?",
"Mẹo: Grab Express giờ sáng đơn nhiều. Chuyển sang GrabFood lúc trưa",
"Be cho phép shipper từ chối đơn không phạt. Thoải mái hơn Grab",
"Confession: Chạy Grab mà hay đi nhầm đường, GPS chỉ tắt vào hẻm cụt",
"Gojek vừa tăng bảo hiểm rider. Cover cả COVID. Good move! 👍",
"Thu nhập Grab tháng 2: 18tr chạy fulltime, 8tr chạy part-time tối",
"Ae Be: App mới có tính năng chat nhóm rider cùng khu vực. Hay!",
"Grab đang test tính năng giao hàng bằng drone ở Q.7. Tương lai đây!",
"Review áo Grab vs áo Be: Grab chất liệu tốt hơn, Be thiết kế đẹp hơn",
"Gojek khu Thủ Đức đơn tăng 50%. Ai rảnh qua đây chạy cùng!",
"Mẹo: Luôn mang theo bag nhiệt khi chạy GrabFood. Đồ nóng = review tốt",
"Be vừa tích hợp thanh toán VNPay. Khách trả online nhiều hơn",
"Confession: Chạy Grab lúc mưa, trượt xe 2 lần. May không sao",
"Ae Grab: Có cách nào lọc đơn theo khoảng cách không? Đơn xa quá",
"Gojek bonus Tết: 5 triệu cho top rider. Ae cày 2 tuần cuối nha!",
"So sánh insurance: Grab cover 50tr tai nạn, Be 30tr, Gojek 40tr",
"Grab mới có tính năng 'Ride Later'. Đặt trước đơn, shipper sắp lịch",
"Ae chạy Be: Khu Phú Nhuận đơn food nhiều nhất. Quán ăn san sát",
"Hôm nay Grab system down 15 phút. Ae nhận đơn Be backup nhé",
"Gojek cho phép rider tự set giá surge. Linh hoạt hơn Grab nhiều",
"Tips: Chạy 3 app cùng lúc Grab+Be+Gojek tối ưu thu nhập",
"Cảm ơn ae Grab-Be-Gojek! Cộng đồng rider mạnh nhất VN 🇻🇳",
],
// Group 3: Shipper Sài Gòn (35)
3 => [
"Sài Gòn mưa bất chợt chiều nay. Ae Q.Bình Thạnh cẩn thận đường ngập!",
"Top 5 quán cơm ngon cho shipper ở Q.1: Cơm Tấm Bụi, Phở Hà, ...",
"Đường Nguyễn Hữu Cảnh sáng nay kẹt 3km vì tai nạn. Đi Điện Biên Phủ",
"Ae SG: Cầu Sài Gòn 2 sắp thông xe. Giao hàng Thủ Đức sẽ nhanh hơn!",
"Ship ở Sài Gòn 5 năm, bản đồ trong đầu thuộc hết. Ae hỏi đường cứ tag",
"Quận 7 Phú Mỹ Hưng cuối tuần rất đông. Ship food thì ok, ship hàng khó đỗ",
"Confession: Yêu Sài Gòn vì 3h sáng vẫn có quán ăn. Shipper đêm sống khỏe",
"Cảnh báo: Đường Trường Chinh Q.Tân Bình đang sửa, kẹt từ 4h-7h chiều",
"Top khu vực ship tốt nhất SG: 1.Q.7 2.Bình Thạnh 3.Thủ Đức 4.Gò Vấp",
"Mưa Sài Gòn 4 tháng liền rồi. Ae nhớ mang áo mưa + túi chống nước",
"Ae Q.12: Đường Tô Ký mới mở rộng, ship nhanh hơn nhiều 🛵",
"Review chỗ đỗ xe miễn phí ở Q.1 cho shipper: Công viên Tao Đàn, bờ kè",
"Sài Gòn đêm 30 Tết: Đường vắng tanh, ship xong ngồi ngắm pháo hoa 🎆",
"Khu Bình Tân: Đơn nhiều, đường xa. Tính ra km cao mà income ổn",
"Ae SG ơi: Chỗ nào rửa xe + thay nhớt rẻ ở khu Gò Vấp?",
"Ship ở Sài Gòn nắng 39°C. Ae nhớ uống nước, đội mũ. Đừng kiệt sức",
"Cầu Thủ Thiêm 2 view đẹp nhất SG. Ship xong đứng ngắm hoàng hôn 🌅",
"Quận 4 đường nhỏ nhưng dân cư đông. Đơn density cao nhất SG",
"Ae Thủ Đức: ĐHQG khu vực này sinh viên order food nhiều. Đơn nhỏ nhưng đều",
"Sài Gòn chiều mưa, shipper vẫn chạy. Respect ae cả nước! 💪",
"Review khu Chợ Bến Thành giao hàng: Tourist tip cao nhưng kẹt xe kinh",
"Ae Q.Tân Phú: Đường Hòa Bình kẹt mỗi sáng. Đi đường Lũy Bán Bích",
"Sài Gòn có quán phở 24/7 ở Q.3. Shipper đêm check in đây nha 🍜",
"Khu Quận 2 (Thủ Đức): Cát Lái, An Phú đơn expat nhiều, tip generous",
"Ship SG 3 năm, mỗi ngày chạy 80-100km. Tổng 100,000km. Vòng quanh VN!",
"Ae SG mùa Tết: Đường về quê kẹt cứng. Ship nội thành thôi cho lành",
"Q.Bình Thạnh Thanh Đa: Bán đảo chỉ 1 đường vào, giao hàng đi vòng",
"Sài Gòn 11h đêm, giao đơn cuối. Về nhà tắm rửa, ngủ. Ngày mai lại chiến!",
"Ae Nhà Bè: Đường về khu công nghiệp vắng đêm, đi cẩn thận",
"Top 3 món ăn vặt SG cho shipper: Bánh tráng, trà sữa, bột chiên",
"Cảnh báo: CSGT đang chốt ở ngã 4 Hàng Xanh. Ae kiểm tra giấy tờ",
"Q.9 cũ (Thủ Đức): KCN cao đơn nhiều giờ trưa, ae tranh thủ",
"Ship Sài Gòn mùa Noel: Đường phố lung linh, giao quà vui lắm 🎄",
"Ae SG: Bao giờ Metro Bến Thành-Suối Tiên chạy? Ship sẽ thay đổi lớn",
"Sài Gòn ơi, cảm ơn vì đã cho shipper cơ hội kiếm sống. Yêu thành phố này ❤️",
],
// Group 4: Shipper Hà Nội (35)
4 => [
"Hà Nội mùa đông rét 8°C mà vẫn ship. Ae nhớ mặc ấm!",
"Đường Giải Phóng kẹt từ 7h-9h. Ae HN nên đi Trương Định thay thế",
"Top khu vực ship tốt nhất HN: Cầu Giấy, Đống Đa, Thanh Xuân",
"Mùa hè HN 40°C. Ship mà như đang nướng. Ai cho xin ly trà đá 🥵",
"Ae Hoàng Mai: Linh Đàm chung cư cao, thang máy chật. Chờ lâu lắm",
"Cầu Nhật Tân chiều thoáng hơn cầu Thanh Trì. Ae note lại",
"Ship HN phố cổ: Đường nhỏ xíu, xe máy vừa đúng 1 chiếc qua",
"Review quán bún chả Hương Liên cho shipper: Ngon, rẻ, nhanh",
"Confession: HN mưa phùn mà ship. Ướt áo nhưng đơn food tăng gấp đôi",
"Ae Long Biên: Cầu Long Biên view sông Hồng đẹp. Ship vừa đi vừa ngắm",
"Khu Tây Hồ: Giao cho expat, đơn giá trị cao, tip bằng USD 💵",
"HN phố đi bộ cuối tuần: Đông nghẹt, ship khu Hoàn Kiếm khó lắm",
"Ae Cầu Giấy: Trần Duy Hưng giờ chiều kẹt 2km. Đi Nguyễn Khang",
"Ship HN mùa thu: Lá vàng rơi, Hồ Tây lãng mạn. Giao hàng cũng thơ 🍂",
"Khu Hà Đông mới phát triển, đường rộng, đơn tăng nhanh. Ae qua thử",
"Ae Ba Đình: Giao hàng gần Lăng Bác, khu vực an ninh cao. Cẩn thận",
"HN nắng hanh 35°C. Ae nhớ bôi kem chống nắng, ship cả ngày da cháy",
"Confession: Ship HN 4 mùa. Xuân mưa, hè nóng, thu gió, đông rét. Khổ!",
"Ae Thanh Xuân: Khu Ngã Tư Sở đông nhất HN. Rush hour kinh khủng",
"Khu Ciputra Nam Thăng Long: Giao hàng cao cấp, bảo vệ check kỹ",
"Ship HN ngày 8/3: Hoa tràn ngập phố, giao hoa cho phụ nữ vui lắm 🌹",
"Ae Đống Đa: Đường Xã Đàn ít kẹt, nối Đống Đa-Thanh Xuân nhanh",
"HN mưa bão tháng 7: Đường ngập, cây đổ. Ae cẩn thận, an toàn là nhất",
"Review cafe cho shipper HN: Highland Coffee wifi free, ngồi nghỉ chân",
"Khu Times City: Chung cư lớn nhất HN, đơn nhiều nhưng phải quen đường",
"Ae HN ship đêm: Phố Tạ Hiện beer đường vui nhưng kẹt. Tránh 8h-11h",
"HN mùa xuân hoa đào nở. Ship mà thấy cây đào đẹp quá dừng lại chụp 📸",
"Confession: Lần đầu ship HN, đi lạc 5 lần vì đường phố cổ giống nhau",
"Ae Gia Lâm: Khu CN Sài Đồng đơn nhiều giờ trưa, ae tranh thủ",
"Ship HN Tết: Chợ hoa Quảng An, chợ Đào Nhật Tân. Đơn hoa tăng 500%",
"Khu Royal City: Parking ngầm rộng, giao hàng đi thang máy. Tiện!",
"Ae HN: Đường sắt trên cao Nhổn-HN ga Cầu Giấy sắp chạy. Đỡ kẹt!",
"HN chiều đông, gió lạnh thổi qua cầu Chương Dương. Ship mà run cầm cập",
"Review bún bò Huế O Xuân cho shipper HN: 35k, ngon, nhanh, no",
"Hà Nội ơi, 36 phố phường đều in dấu chân shipper. Yêu HN! ❤️",
],
// Group 5: Review Đồ Ship (35)
5 => [
"Review túi ship 60L Lalamove: Chống nước tốt, 6 ngăn, giá 180k ⭐⭐⭐⭐",
"So sánh 3 loại áo khoác UV cho shipper: Uniqlo, Coolmate, no-brand",
"Review nón fullface Yohe 878: Nhẹ 1.2kg, kính chống sương, 450k",
"Đánh giá sạc dự phòng Anker 20000mAh: Pin khỏe, sạc 2 lần, 350k",
"Review Wave Alpha 2020 sau 50,000km: Máy bền, xăng 1.5L/100km",
"So sánh găng tay chống nắng: Loại 50k vs 150k. Đáng tiền hơn?",
"Review tai nghe bluetooth JBL T110BT: Nghe gọi clear, pin 6h, 400k",
"Đánh giá bao tay chống nước 3M: Ship mưa tay khô, grip tốt, 80k",
"Review bình nước giữ lạnh Lock&Lock: 12h lạnh, 500ml, 120k",
"So sánh dầu nhớt: Castrol vs Motul vs Shell Advance cho xe Wave",
"Review điện thoại Redmi Note 13: Pin 5000mAh, 2 ngày, giá 4tr",
"Đánh giá lốp Michelin City Extra: Bám đường mưa, 300k/cặp",
"Review áo mưa Rando vs áo mưa Sơn Thủy: Chất lượng vs giá cả",
"So sánh túi giữ nhiệt: Loại foam vs loại vải. Food hot or cold?",
"Review khóa chống trộm xe Viro Smart Lock: 500k, bluetooth, hay!",
"Đánh giá kính mát polarized cho shipper: Chống chói, lái xe safe",
"Review Air Blade 2024: Nhanh, đẹp nhưng tốn xăng hơn Wave",
"So sánh app GPS: Google Maps vs Waze vs HERE cho shipper VN",
"Review thùng ship inox: Bền, chống nước, nhưng nặng 3kg. 250k",
"Đánh giá áo phản quang 3M: Ship đêm an toàn, 60k. Must have!",
"Review miếng lót yên xe chống nóng: 30k mà hiệu quả cao",
"So sánh 3 loại balo ship: Standard vs Premium vs Pro",
"Review camera hành trình cho xe máy: Bằng chứng tai nạn, 500k",
"Đánh giá đèn pin Fenix cho ship đêm: 1000 lumen, pin 8h, 300k",
"Review dép Crocs cho shipper: Thoải mái, chống trượt, 350k",
"So sánh pin sạc dự phòng: 10000 vs 20000 vs 30000mAh",
"Review quần short thể thao cho ship mùa hè: Thoáng mát, 150k",
"Đánh giá tool kit mini cho xe máy: Cờ lê, tuốc nơ vít, 80k",
"Review kính chắn gió xe máy: Chống bụi, chống mưa. 200k",
"So sánh 5 loại kem chống nắng: Neutrogena vs Anessa vs Skin1004",
"Review giày thể thao Nike Revolution cho shipper: Êm, bền, 800k",
"Đánh giá đồng hồ thông minh Mi Band 8: Track sức khỏe, 700k",
"Review khẩu trang vải 3 lớp cho ship: Thở thoải mái, giặt được",
"So sánh 3 loại bọc yên xe chống nắng: Giá vs chất lượng",
"Tổng hợp: Top 10 đồ ship MUST HAVE cho shipper mới. Save lại! 📌",
],
// Group 6: Confession Shipper (35)
6 => [
"Confession: Ship 3 năm, lưng còng, đầu gối đau. Nhưng không hối hận",
"Thú nhận: Có lần giao hàng cho crush cũ. Awkward 10 giây 😂",
"Confession: Ngày nào cũng hẹn bạn gái nhưng ship xong là 10h đêm 😢",
"Thú nhận: Mình hay khóc trên đường giao hàng vì áp lực. Ae có vậy không?",
"Confession: Ship COD 5 triệu mà ví chỉ có 200k. Tim đập suốt đường",
"Thú nhận: 3h sáng vẫn ship vì hứa với khách. Mệt mà không bỏ được",
"Confession: Có hôm buồn ngủ quá ngủ gục 15 phút ở công viên",
"Thú nhận: Ganh tỵ với bạn bè ngồi văn phòng máy lạnh. Nhưng tự do hơn",
"Confession: Giao nhầm đơn COD 2 triệu. Phải bù tiền túi 💸",
"Thú nhận: Ship cho người yêu cũ mà phải giả vờ không biết 😅",
"Confession: Ăn trộm 1 miếng bánh trong đơn giao. Xin lỗi khách 😭",
"Thú nhận: Ngủ quên alarm, mất 3 đơn sáng. Tự trách mình cả ngày",
"Confession: Ship 4 năm rồi vẫn chưa có người yêu. Ai rảnh đâu hẹn hò",
"Thú nhận: Lương cao nhất 32tr. Thấp nhất 8tr. Nghề phập phồng!",
"Confession: Suýt tông cột đèn vì buồn ngủ. Từ đó mình nghỉ khi mệt",
"Thú nhận: Xe hết xăng giữa đường, dắt bộ 2km. Xấu hổ ghê 😂",
"Confession: Giao cho bạn thân mà không nhận ra. Gặp nhau ngỡ ngàng",
"Thú nhận: Ship xong mệt quá mà vẫn phải nấu cơm cho gia đình",
"Confession: Có lần ước bỏ ship. Nhưng nghĩ lại tiền thì cố tiếp",
"Thú nhận: Ship hàng quý mà làm rớt. Tim đứng 1 nhịp. May không sao",
"Confession: Đã từng ship nhầm thành phố vì GPS chỉ sai tỉnh 😱",
"Thú nhận: Ngày cuối ship trước khi chuyển nghề. 5 năm, 50k đơn. Nhớ!",
"Confession: Ship cho viện dưỡng lão, cụ mời uống trà. Khóc vì cảm động",
"Thú nhận: Thấy shipper khác bị tai nạn, dừng lại giúp mà trễ 5 đơn",
"Confession: Giao đồ cho đám cưới 100 phần. Hoa mắt xếp xe!",
"Thú nhận: Ship 6 tháng mới biết có nút tắt thông báo app 😅",
"Confession: Bấm hoàn thành đơn nhưng quên giao. Chạy lại lúc 10h đêm",
"Thú nhận: Ship 2000 đơn/tháng 6 tháng liền. Nhận badge VIP. Tự hào!",
"Confession: Giao cho em bé, em tip 5k và nói 'Anh vất vả quá' 😢",
"Thú nhận: Shipper mà hay ăn vặt. Mỗi ngày ghé 3-4 quán dọc đường",
"Confession: Trượt xe 2 lần trong mưa. May mắn không sao. Cẩn thận!",
"Thú nhận: Ship cho nhà sách, giao 50 cuốn nặng 20kg lên lầu 5 🏋️",
"Confession: Giao cho bà cụ ở 1 mình, giúp bà xách đồ. Ấm lòng ❤️",
"Thú nhận: 12h đêm giao đơn cuối. Về nhà con đã ngủ. Nhớ con quá",
"Confession cuối: Yêu nghề shipper vì tự do, vì đường, vì mọi người ❤️🇻🇳",
],
// Group 7: Mẹo Tiết Kiệm Xăng (35)
7 => [
"Mẹo #1: Tắt máy khi dừng đèn đỏ trên 30 giây. Tiết kiệm 15%/tháng",
"So sánh xăng: E5 RON 92 tiết kiệm 10% so với RON 95. Mình chạy E5",
"Mẹo #2: Giữ tốc độ 40-50km/h ổn định. Tăng giảm ga liên tục tốn xăng",
"Thay nhớt đúng kỳ (1500-2000km) giúp máy chạy mượt, ít tốn xăng",
"Mẹo #3: Kiểm tra áp suất lốp mỗi tuần. Lốp non tốn thêm 10% xăng",
"Bơm lốp đúng PSI: Wave 28-32, Air Blade 30-33, Exciter 29-33",
"Mẹo #4: Sắp xếp đơn theo route, không chạy lung tung. Tiết kiệm 20km/ngày",
"App tính route tối ưu cho shipper: Route4Me, Circuit. Đã test hiệu quả",
"Mẹo #5: Không chở nặng quá tải. Thùng ship + hàng max 30kg thôi",
"Thay bugi mới mỗi 10,000km. Bugi cũ đốt xăng kém, tốn thêm 15%",
"Mẹo #6: Đổ xăng lúc sáng sớm hoặc tối mát. Xăng nở khi nóng",
"Xăng E5 vs RON 95: Test 1 tháng, E5 tiết kiệm 180k. Không hại máy",
"Mẹo #7: Không warm up xe quá 30 giây. Xe đời mới không cần nổ máy lâu",
"Kinh nghiệm: Wave Alpha 1.5L/100km, Air Blade 2L/100km, Exciter 2.5L",
"Mẹo #8: Vệ sinh kim phun xăng mỗi 5000km. Đốt cháy hoàn toàn hơn",
"Chi phí xăng shipper: Trung bình 2-3 triệu/tháng. Tiết kiệm được 500k",
"Mẹo #9: Chạy eco mode nếu xe có. Tiết kiệm 10-15% so với sport mode",
"Đổ xăng bao nhiêu lít/ lần? Mình đổ 3L mỗi lần, 2 lần/ngày",
"Mẹo #10: Tránh giờ kẹt xe. Kẹt xe = nổ máy dừng = tốn xăng vô ích",
"Xe điện VinFast Evo cho shipper: 0 đồng xăng, sạc 1 lần chạy 80km",
"Mẹo #11: Sử dụng phanh engine khi xuống dốc. Không tốn xăng!",
"Phụ tùng ảnh hưởng xăng: Lọc gió bẩn tốn 10%, chain lỏng tốn 5%",
"Mẹo #12: Đậu xe chỗ râm mát. Xăng bay hơi khi nắng nóng",
"Test: Đi 1km mất bao nhiêu xăng? Wave: 15ml, Air Blade: 20ml",
"Mẹo #13: Không ga trước khi tắt máy. Lãng phí xăng vô ích",
"Xe số tiết kiệm hơn xe ga 20-30%. Shipper chạy nhiều nên cân nhắc",
"Mẹo #14: Check xe định kỳ 3 tháng/lần. Máy ngon = xăng ít",
"App đo tiêu hao xăng: Fuelio, Drivvo. Track chi phí chính xác",
"Mẹo #15: Khi dừng lâu (giao hàng, chờ khách) tắt máy. 5p = 50ml",
"Tổng kết: Áp dụng 15 mẹo, mình tiết kiệm 600k xăng/tháng 🎉",
"Lốp mới vs lốp cũ: Lốp mòn tốn xăng hơn 8%. Thay khi mòn 70%",
"Mẹo đổ xăng: Đổ ở trạm uy tín, tránh xăng pha. Xăng pha hại máy",
"Xe Winner X cho shipper: Khỏe, nhanh nhưng tốn xăng 2.8L/100km",
"Mẹo bonus: Rửa xe sạch giảm lực cản gió, tiết kiệm xăng nhẹ",
"Tổng hợp: 15 mẹo tiết kiệm xăng cho shipper. Save và chia sẻ! 📌💰",
],
// Group 8: Shipper J&T SPX Ninja Van (35)  
8 => [
"J&T vừa tăng chiết khấu 3% cho shipper rating 4.7+. Ae cố lên!",
"SPX app mới update: Giao diện đẹp hơn, nhưng lag trên Android cũ",
"Ninja Van khu Bình Dương đơn tăng mạnh. Ai qua đây chạy cùng?",
"So sánh: J&T đơn nhiều, SPX phí cao, Ninja Van linh hoạt giờ giấc",
"J&T thưởng Tết 2 triệu cho shipper trên 1500 đơn/tháng 🎉",
"SPX giao hàng Shopee: Đơn nhỏ nhưng lượng lớn. Chạy hết ngày!",
"Ninja Van cho ship đến 11h đêm. Linh hoạt hơn J&T và SPX",
"Review app J&T: UI tốt, GPS chính xác, nhưng cần thêm filter đơn",
"SPX support chậm quá. Ticket 3 ngày chưa reply. Ae có bị vậy?",
"Ninja Van mới có tính năng auto-route. Sắp xếp đơn theo tuyến 🗺️",
"J&T khu Q.7 HCM: Đơn trung bình 40/ngày. Kiếm 15-18tr/tháng",
"SPX siêu sale 3.3: Đơn tăng 300%. Mệt nhưng túi đầy tiền!",
"Ninja Van cho phép reject đơn quá xa. J&T và SPX thì bị trừ điểm",
"Hỏi: J&T tính phí thế nào? Theo km hay theo kích thước kiện?",
"SPX Black Friday: Kho hàng chất đống, shipper làm 14h/ngày",
"Ninja Van bonus tháng: 1.5 triệu cho 800 đơn. Ae cày đi!",
"J&T vs Ninja Van: J&T kho gần hơn, Ninja Van chiết khấu cao hơn",
"SPX app crash lúc 8h sáng hôm nay. Mất 5 đơn vì không nhận kịp",
"Ninja Van mới mở hub ở Thủ Đức. Nhận hàng gần hơn 5km!",
"J&T cho shipper mượn thùng ship miễn phí. SPX phải tự mua",
"SPX giao cho Shopee Express: Đơn COD trả tiền nhanh, 24h",
"Ninja Van chiết khấu shipper mới: 2 tuần đầu bonus 50%",
"J&T khu Gò Vấp: Kho mới mở, nhận đơn sáng 6h. Ae đến sớm!",
"SPX tip: Nhận đơn theo cluster, giao 1 khu trước rồi sang khu khác",
"Ninja Van ship quốc tế Singapore-VN. Đơn giá trị cao!",
"So sánh bảo hiểm: J&T 30tr, SPX 25tr, Ninja Van 35tr",
"J&T ngày lễ đơn tăng 200%. Ae chuẩn bị sức khỏe!",
"SPX khu Bình Thạnh: Nhiều chung cư, đơn density cao",
"Ninja Van rating system fair hơn J&T. Khách cancel không ảnh hưởng",
"J&T mới thêm giao hàng nặng (>30kg). Phí cao gấp 3 nhưng đáng!",
"SPX Tết: Kho đóng cửa 3 ngày. Ae tranh thủ nghỉ ngơi",
"Ninja Van app tính quãng đường chính xác. Không bị thiếu km như SPX",
"J&T shipper VIP: Ưu tiên đơn tốt, chiết khấu +5%. Cần 2000 đơn/tháng",
"SPX tip: Giao đơn hoàn nhanh để giữ KPI. Đừng delay quá 1 ngày",
"Cảm ơn ae J&T, SPX, Ninja Van! Cộng đồng mạnh nhất 💪",
],
// Group 9: Tips Giao Hàng Nhanh (35)
9 => [
"Tip #1: Sắp xếp hàng trong thùng theo thứ tự giao. Đơn giao trước ở trên",
"Tip #2: Luôn gọi trước khách 5 phút. Tránh chờ đợi lãng phí",
"Tip #3: Học thuộc hẻm khu vực mình ship. GPS không biết hẻm nhỏ",
"Tip #4: Giao đơn COD chuẩn bị tiền lẻ sẵn. Khách ghét chờ thối tiền",
"Tip #5: Check đơn kỹ trước khi rời kho. Thiếu hàng = quay lại = mất 30p",
"Tip #6: Chụp ảnh giao hàng mỗi đơn. Bằng chứng khi khách khiếu nại",
"Tip #7: Mặc áo gọn gàng, sạch sẽ. First impression quan trọng!",
"Tip #8: Dùng Google Maps + Waze cùng lúc. GM đường lớn, Waze hẻm nhỏ",
"Tip #9: Nhận đơn theo cluster, không nhận đơn xa rải rác",
"Tip #10: Giao đơn gấp trước, đơn flex sau. Ưu tiên = rating cao",
"Mẹo: Luôn sạc pin 100% trước khi ra đường. Pin < 20% = anxiety!",
"Tip #11: Học cách giao tiếp lịch sự. 'Anh/chị ơi' thay vì 'Ê ship'",
"Tip #12: Biết đường tắt khu vực mình. Tắt 1km = tiết kiệm 10 phút",
"Tip #13: Giao hàng dễ vỡ: Quấn bóng khí, đặt đứng, không chồng",
"Tip #14: Ship food: Giữ nóng/lạnh, không nghiêng, giao < 30 phút",
"Mẹo: Mang theo băng keo + dây chun. 2 vật cứu mạng shipper!",
"Tip #15: Xử lý khách khó: Bình tĩnh, lịch sự, nhờ support nếu cần",
"Tip #16: Ghi nhớ số nhà khách quen. Lần sau giao nhanh hơn",
"Tip #17: Ship mưa: Bọc hàng bằng nilon, đi chậm, bật đèn",
"Tip #18: Ship đêm: Đèn pin, áo phản quang, đi đường lớn",
"Mẹo: Uống đủ nước, ăn đủ bữa. Ship 10h mà không ăn = kiệt sức",
"Tip #19: Báo khách khi gần đến. Tin nhắn: 'Em đang đến, 5p nữa ạ'",
"Tip #20: Không nhận quá 40 đơn/ngày khi mới. Quen rồi mới tăng",
"Tip #21: Giao cho chung cư: Gọi trước, hẹn lobby, tránh chờ thang máy",
"Tip #22: COD lớn: Kiểm tra tiền kỹ, đếm trước mặt khách",
"Mẹo pro: Mua sạc dự phòng 20000mAh. Ship cả ngày không lo hết pin",
"Tip #23: Xử lý hàng hư: Chụp ảnh, báo kho ngay. Không tự ý giao",
"Tip #24: Peak hour: 11h-13h (food), 17h-19h (express). Tập trung!",
"Tip #25: Tip từ khách: Cảm ơn chân thành, nhớ mặt khách tip cao 😄",
"Tip #26: Quản lý tiền COD: Tách riêng ví ship, không lẫn tiền cá nhân",
"Mẹo: Mang theo áo thun dự phòng. Mồ hôi mùa hè = thay áo giữa ngày",
"Tip #27: Giao hàng quốc tế: Check giấy tờ hải quan, invoice đầy đủ",
"Tip #28: Mùa sale: Chuẩn bị trước 1 tuần, sạc pin, check xe",
"Tip #29: Rating thấp: Đọc review khách, cải thiện từng điểm nhỏ",
"Tổng hợp 29 tips giao hàng nhanh. Shipper mới PHẢI đọc! Save lại 📌",
],
// Group 10: Hỏi Đáp Shipper (35)
10 => [
"Hỏi: Shipper mới nên bắt đầu với hãng nào? GHTK hay GHN?",
"Hỏi: Thu nhập shipper trung bình ở HCM bao nhiêu/tháng?",
"Hỏi: Có cần GPLX hạng gì để ship? A1 hay A2?",
"Hỏi: Ship bằng xe điện có được không? Hãng nào chấp nhận?",
"Hỏi: Bảo hiểm y tế cho shipper tự do. Đăng ký ở đâu?",
"Hỏi: Thuế thu nhập cho shipper tính sao? Trên 100tr/năm phải đóng?",
"Hỏi: Xe nào tốt nhất cho shipper mới? Budget 20 triệu",
"Hỏi: Làm shipper part-time được không? Chỉ chạy tối 5h-10h",
"Hỏi: COD là gì? Quy trình COD cho shipper mới thế nào?",
"Hỏi: Bị khách boom hàng xử lý sao? Hãng có bồi thường không?",
"Hỏi: Shipper có được nghỉ phép không? Chạy freelance mà",
"Hỏi: Giao hàng quá khổ (tivi, nội thất) phí tính sao?",
"Hỏi: Rating shipper quan trọng không? Dưới 4.0 có bị cắt đơn?",
"Hỏi: Shipper nữ có an toàn không? Ae nữ chia sẻ kinh nghiệm",
"Hỏi: Đăng ký nhiều hãng cùng lúc được không? GHTK + GHN + Grab?",
"Hỏi: Shipper cần giấy tờ gì? CMND, GPLX, đăng ký xe, gì nữa?",
"Hỏi: Ship hàng lạnh (kem, frozen) cần túi giữ nhiệt loại nào?",
"Hỏi: Xăng 1 ngày hết bao nhiêu? Chi phí xăng trung bình?",
"Hỏi: Shipper bị tai nạn khi đang giao. Ai chịu trách nhiệm?",
"Hỏi: Thời gian linh hoạt nhất để chạy ship? Sáng, trưa hay tối?",
"Hỏi: Mua bảo hiểm xe máy ở đâu rẻ? Bắt buộc hay tự nguyện?",
"Hỏi: Shipper có cần thành lập hộ kinh doanh không?",
"Hỏi: App nào track quãng đường + thu nhập cho shipper?",
"Hỏi: Giao hàng COD 10 triệu+, cần bảo hiểm riêng không?",
"Hỏi: Đi ship Tết có phụ thu không? Phụ thu bao nhiêu?",
"Hỏi: Shipper có được vào khu chung cư không? Bảo vệ hay cản",
"Hỏi: Mình 18 tuổi có đi ship được chưa? Cần bao nhiêu tuổi?",
"Hỏi: Ship xuyên tỉnh HCM-Bình Dương phí thế nào?",
"Hỏi: Ae ship bao lâu thì mua được xe mới? Tiết kiệm được bao nhiêu?",
"Hỏi: Shipper bị phạt vì lý do gì thường nhất? Cách tránh?",
"Hỏi: Giao hàng cho công ty cần invoice VAT không?",
"Hỏi: Shipper có nên đầu tư xe tay ga đắt tiền hơn không?",
"Hỏi: Khu vực nào ở HN ship kiếm nhiều nhất?",
"Hỏi: Ship đêm an toàn không? Cần chuẩn bị gì?",
"Hỏi ae senior: Bí quyết ship 50+ đơn/ngày mà không kiệt sức?",
],
// Group 11: Shipper Đà Nẵng (35)
11 => [
"Ae ĐN: Mùa du lịch bắt đầu rồi. Đơn food tăng 50%! 🏖️",
"Đường Trần Phú ĐN sáng nay kẹt vì sự kiện. Đi đường 2/9 thay thế",
"Ship ĐN mùa mưa bão: Cẩn thận gió mạnh khi qua cầu Rồng 🌊",
"Top khu ship tốt nhất ĐN: Hải Châu, Sơn Trà, Thanh Khê",
"Review quán mì Quảng ngon cho shipper ĐN: Quán Bà Vị, 25k",
"Cầu Rồng ĐN cuối tuần phun lửa. Ship xong đứng xem free show 🐉🔥",
"Ae Sơn Trà: Khu resort đơn food cao cấp, tip generous!",
"ĐN nhỏ gọn, ship 30 phút là xuyên thành phố. Sướng hơn SG nhiều",
"Bán đảo Sơn Trà cấm xe máy. Đơn khu này phải giao dưới chân núi",
"Ae ĐN: Chợ Hàn cuối tuần tourist nhiều. Đơn souvenir tăng mạnh",
"Ship ĐN mùa hè biển đẹp. Giao xong tắm biển Mỹ Khê 10 phút 🏊",
"Khu Ngũ Hành Sơn: Đơn marble shop nhiều, hàng nặng nhưng phí cao",
"Confession ĐN: Ship ở thành phố đáng sống. View biển mỗi ngày đi làm",
"Ae ĐN: Đường Nguyễn Văn Linh kẹt 5h chiều. Đi ven biển Hoàng Sa",
"Bãi biển Mỹ Khê nằm trong top 10 đẹp nhất châu Á. Ship đây sướng!",
"Khu APEC ĐN: Giao cho resort 5 sao. An ninh cao, tip generous",
"Ship ĐN qua Hội An: 30km nhưng đường đẹp. Đơn Hội An tip du khách!",
"Ae ĐN: App Be mới mở ở đây. Ít cạnh tranh, ae đăng ký sớm",
"Mùa pháo hoa ĐN: Đường cấm xe, đơn khu trung tâm khó giao",
"Review bún mắm ĐN cho shipper: Quán Cô Ba, 30k, ngon hết sảy",
"Cầu Trần Thị Lý ĐN view đẹp ban đêm. Ship tối ngang qua chụp ảnh 📸",
"Ae ĐN: Khu FPT City đơn tech nhiều, shipper cần biết dùng app",
"Ship ĐN mùa Tết: Bánh tráng cuốn thịt heo, mì Quảng ship khắp nơi",
"Khu Liên Chiểu: KCN đơn nhiều giờ trưa, ae tranh thủ",
"Ae ĐN: Đường hầm Hải Vân cấm xe máy. Ship Huế-ĐN phải đi đèo",
"Thu nhập ship ĐN: 12-15tr/tháng, chi phí thấp hơn SG 30%",
"ĐN nhỏ nhưng xinh. Dân hiền, khách dễ thương. Ship vui lắm!",
"Ae ĐN cuối tuần: Asia Park đơn food tăng. Khu vui chơi = đơn nhiều",
"Khu Hòa Khánh ĐN: Chung cư mới, dân cư đông, đơn tăng nhanh",
"Ship ĐN qua Bà Nà Hills: Đường đèo khó, nhưng view đẹp mê 🏔️",
"Ae ĐN: Bãi biển Non Nước ít du khách hơn Mỹ Khê, nhưng yên bình",
"Thu nhập top shipper ĐN: 20tr/tháng. Chạy 10h, 30 đơn/ngày",
"Confession ĐN: Ship 2 năm, yêu thành phố này hơn bất kỳ nơi nào",
"Ae ĐN mùa mưa: Tháng 10-12 mưa nhiều, chuẩn bị áo mưa + túi nilon",
"Đà Nẵng: Thành phố đáng sống, đáng ship! Cảm ơn ae ĐN ❤️🏖️",
],
// Group 12: Đồ Nghề Shipper (35)
12 => [
"Bán thùng ship 60L còn mới 90%. Chống nước tốt. Giá 120k. Inbox!",
"Thanh lý áo khoác UV Uniqlo size L. Mặc 2 tháng. 200k (mua 500k)",
"Bán sạc dự phòng Anker 20000mAh còn bảo hành. 250k ship free",
"Cần mua xe Wave Alpha secondhand. Budget 15-18tr. Ai bán inbox",
"Thanh lý nón fullface Yohe 878 đen. Mới 95%. 350k (mua 500k)",
"Bán 2 đôi găng tay chống nắng mới. 40k/đôi hoặc 70k cả 2",
"Cần mua thùng ship inox secondhand. Ai bán ở khu HCM inbox",
"Thanh lý bình nước giữ lạnh Lock&Lock 500ml. 80k. Khu Q.7",
"Bán kính mát polarized cho shipper. Chống chói UV400. 100k",
"Cần mua túi giữ nhiệt cho food delivery. Budget 100-150k",
"Thanh lý áo mưa Rando bộ 2 chiếc. 50k/bộ. Khu Gò Vấp",
"Bán camera hành trình cho xe máy. Quay full HD. 400k",
"Cần mua lốp Michelin City Extra cho Wave. Ai biết chỗ rẻ?",
"Thanh lý đồng hồ Mi Band 8. Pin 14 ngày. 500k (mua 800k)",
"Bán khóa chống trộm Viro Smart Lock. 400k. Khu Bình Thạnh",
"Cần mua áo phản quang 3M. Ship đêm cần. Ai có bán?",
"Thanh lý 3 cái bọc yên xe chống nóng. 20k/cái. Lấy hết 50k",
"Bán tool kit mini cho xe máy: Cờ lê, tuốc nơ vít. 60k",
"Cần mua điện thoại secondhand pin khỏe cho ship. Budget 2-3tr",
"Thanh lý giày thể thao Nike Revolution. Size 42. 500k",
"Bán quần short thể thao Coolmate. Thoáng mát ship hè. 100k",
"Cần mua balance đứng cho shipper. Chữa đau lưng. Ai có?",
"Thanh lý 5 cái khẩu trang vải 3 lớp. 15k/cái. Ship free HCM",
"Bán tai nghe bluetooth QCY T13 ANC. Pin 7h. 200k",
"Cần mua thùng giữ lạnh cho ship kem/frozen. 20L. Ai bán?",
"Thanh lý sạc xe 2 cổng QC3.0. 70k. Sạc nhanh trên xe",
"Bán dép Crocs secondhand. Size 41. 200k (mua 400k)",
"Cần mua đèn pin Fenix cho ship đêm. Budget 200-300k",
"Thanh lý balo ship Premium 80L. Còn mới 85%. 200k",
"Bán dây chun + băng keo shipper combo. 30k/set. Mua 5 free 1",
"Cần mua kính chắn gió xe máy. Chống bụi + mưa. Budget 200k",
"Thanh lý kem chống nắng Anessa 60ml. Còn 70%. 150k",
"Bán pin sạc dự phòng Xiaomi 30000mAh. 300k. Khu Tân Bình",
"Cần mua áo khoác chống nước cho mùa mưa. Budget 200-300k",
"📢 Đăng tin mua bán đồ ship tại đây! Ae cùng hỗ trợ nhau 🤝",
],
];

// Process batch
$batchGroups = [];
if($batch==1) $batchGroups=[1,2,3];
elseif($batch==2) $batchGroups=[4,5,6];
elseif($batch==3) $batchGroups=[7,8,9];
elseif($batch==4) $batchGroups=[10,11,12];
else{echo "All batches done\n";exit;}

$userIds=$d->fetchAll("SELECT id FROM users WHERE id > 1 ORDER BY RAND() LIMIT 200");
$uids=array_column($userIds,'id');
$imgDir='/home/nhshiw2j/public_html/uploads/posts/';
$imgs=[];foreach(glob($imgDir.'seed_*.jpg') as $f){$imgs[]='/uploads/posts/'.basename($f);}
$cmts=['Đúng rồi bạn!','Hay quá 👍','Cảm ơn chia sẻ','Like mạnh!','Shipper cố lên 💪','Mình cũng vậy','Kinh nghiệm quý','Ae đoàn kết!','Bookmark lại','Chia sẻ thêm đi','Thanks bạn!','Confirm đúng!','Good job!','Respect ae!','Keep going!'];

$pdo->beginTransaction();
try{
$totalIns=0;$totalLk=0;$totalCmt=0;
foreach($batchGroups as $gid){
    $posts=$groupPosts[$gid] ?? [];
    echo "Group $gid: ".count($posts)." posts\n";
    foreach($posts as $content){
        $uid=$uids[array_rand($uids)];
        $imgJson=(rand(1,100)<=70&&count($imgs)>0)?json_encode([$imgs[array_rand($imgs)]]):null;
        $likes=rand(5,180);$comments=rand(1,30);$shares=rand(0,15);
        $ca=date('Y-m-d H:i:s',time()-rand(1,720)*3600);
        $pdo->prepare("INSERT INTO group_posts (group_id,user_id,content,images,type,likes_count,comments_count,shares_count,`status`,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)")
            ->execute([$gid,$uid,$content,$imgJson,'post',$likes,$comments,$shares,'active',$ca]);
        $pid=$pdo->lastInsertId();
        $totalIns++;
        // Likes
        $nl=rand(3,8);$likers=array_rand(array_flip($uids),min($nl,count($uids)));
        if(!is_array($likers))$likers=[$likers];
        foreach($likers as $lu){$pdo->prepare("INSERT IGNORE INTO group_post_likes (post_id,user_id,created_at) VALUES (?,?,NOW())")->execute([$pid,$lu]);$totalLk++;}
        // Comments
        $nc=rand(1,4);
        for($j=0;$j<$nc;$j++){
            $cu=$uids[array_rand($uids)];
            $pdo->prepare("INSERT INTO group_post_comments (post_id,user_id,content,`status`,created_at) VALUES (?,?,?,'active',?)")
                ->execute([$pid,$cu,$cmts[array_rand($cmts)],date('Y-m-d H:i:s',time()-rand(60,86400))]);
            $totalCmt++;
        }
    }
    // Update post_count
    $cnt=$d->fetchOne("SELECT COUNT(*) as c FROM group_posts WHERE group_id=? AND `status`='active'",[$gid])['c'];
    $d->query("UPDATE `groups` SET post_count=? WHERE id=?",[$cnt,$gid]);
}
$pdo->commit();
echo "\nBatch $batch: $totalIns posts, $totalLk likes, $totalCmt comments\n";
echo "Total group_posts: ".$d->fetchOne("SELECT COUNT(*) as c FROM group_posts")['c']."\n";
}catch(Exception $e){$pdo->rollback();echo "ERROR: ".$e->getMessage()."\n";}
